### ISSUE TITLE
Conda environment setup does not work

### ISSUE THREAD

**Issue by brystingjosephine** [nrbennet/dl_binder_design#39]
1. The Issue is regarding (from Guthub Page):
"Your ~/.condarc should look something like this:
channels: 
- https://USERNAME:PASSWORD@conda.graylab.jhu.edu
- conda-forge
- defaults"

2. My ~/. condarc looks as follows:
(base) [brysting@seneca include]$ conda config --show channels
channels:
  - https://levinthal:paradox@conda.rosettacommons.org
  - conda-forge
  - defaults

3. Yet, when I set up the environment, I get an error:

(base) [brysting@seneca include]$ conda env create -f dl_binder_design_original.yml

Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
                                                                                             
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.graylab.jhu.edu/linux-64/pyrosetta-2023.33 release.9c16e13-py39_0.tar.bz2>
Elapsed: 00:00.327765

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by nrbennet** [comment]
I have updated these environments to be easier to install. This specific error is due to you not having the username and password required to install PyRosetta. These need to be added to your condarc like this:
- https://USERNAME:PASSWORD@conda.graylab.jhu.edu

You can get a PyRosetta license for free as an academic here: https://graylab.jhu.edu/pyrosetta/downloads/documentation/PyRosetta_Install_Tutorial.pdf
