### ISSUE TITLE
Running with alternate AF2 models

### ISSUE THREAD

**Issue by swanss** [nrbennet/dl_binder_design#4]
Hi Nate,

Thanks for making this available! I was able to get it up and running on my own system very easily and it seems to be working well.  I was wondering if you have explored using other alphafold models. Based on the code, it seems like it is set up to only use the model_1_ptm model. 

- Do you have a sense of whether there's a benefit to using all five of the monomer_ptm models?
- What about the multimer model? I'm curious if it would work better, but there is also the issue that it was trained on some of complexes I'm testing, which confounds the analysis

Lastly, I've noticed that the runtimes reported in the out.sc file can vary from ~5 s to > 90 s. Is this something you've seen too?

**Comment by zackmawaldi** [comment]
Interested to learn more behind using `model_1_ptm` only as well. My guess it's a computational/time saving measure. Would love to hear from Nate on this!

**Comment by nrbennet** [comment]
The code can be modified to run models other than `model_1_ptm`. The only other model which was trained with template information was `model_2_ptm`. Since templates and pAE are critical parts of the filtering protocol we describe here, these are the only two models which can be used. There is little difference between the two models' performance and combining the scores from the two models did not help with in silico filtering performance.

I have looked at whether multimer (v < 3) improved on this filtering task and didn't find that it did better. I have a version of this script with multimerv3 implemented but have not extensively benchmarked it on this task. I don't expect it to be much of an improvement.
