### ISSUE TITLE
Minimized AF2 predictions

### ISSUE THREAD

**Issue by almeida85** [nrbennet/dl_binder_design#51]
Hello,

I am doing some testing of the code with several hundreds of designs of 7-15 residues peptidic binders targeting a GPCR I used hotspots to define the binding site during the RFDiffusion prediction. 
During the AF2 step, I found major clashes in almost all of them. The lowest PAE_interaction value I have until now is 12.4. Are the AF2 predictions minimized/relaxed? 

Thanks in advance.

**Comment by nrbennet** [comment]
The AF2 predictions are not minimized but we find that when pAE is good (<10) the structures can be minimized to not have clashes. AF2 is known to generate clashing side chains before minimization since it is operating in a constrained torsional space for side chains but these side chains can often be quickly minimized to have no clashes.

I would just filter by pAE unless you are trying to get a Rosetta ddG value, in which case you will need to minimize to have a meaningful ddG.

**Comment by almeida85** [comment]
Thanks
